manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  kinematics_solver_geometric_parameters:
      a1:  0.05
      a2:  0.0
      b:   0.050
      c1:  0.478
      c2:  0.500
      c3:  0.550
      c4:  0.100
  kinematics_solver_joint_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  kinematics_solver_joint_sign_corrections: [1, 1, 1, 1, 1, 1]
